### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by bestsoft100** [architectury/architectury-api#106]
Game crashes, I only have this mod and the newest fabric installed.
I'm using java 17 early access, but I also tried java 16

https://pastebin.com/6viamMip

**Comment by warjort** [comment]
The error message is kind of misleading.
The real issue here is the mixin config hasn't been updated to say it needs JAVA_16
https://github.com/architectury/architectury-api/blob/56ebb43da40684e8d4093eb698ce6bd0fb9bc62d/common/src/main/resources/architectury-common.mixins.json#L4

You won't see this error if you have another mod installed that does specify JAVA_16, e.g. the fabric-api.

**Comment by MaxNeedsSnacks** [comment]
Urgh, good catch, forgot to migrate this, hold on

**Comment by MaxNeedsSnacks** [comment]
https://github.com/architectury/architectury-api/commit/cccdb141f28b1b20179e298487fd0029ebb86fa8
